# -*- coding: utf-8 -*-
"""stopwords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18dP86VUpV6ZzCSQiU9oSdMHQsgJZ66NC
"""

import nltk
nltk.download('punkt')

a=""""A Content Writer is a professional who writes informative and engaging articles to help brands showcase their products. They write on a range of subjects and are responsible for creating the best possible written or visual content, from blog posts to press releases


 

"""

from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize

"text = Nick likes to play football, however he  is not too fond  fever\n  of tennis."
text_tokens = word_tokenize(a)

tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]

print(tokens_without_sw)

filtered_sentence = (" ").join(tokens_without_sw)
print(filtered_sentence)

from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize

"text = Nick likes to play football, however he  is not too fond  fever\n  of tennis."
text_tokens = word_tokenize(a)

tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]

print(tokens_without_sw)

filtered_sentence = (" ").join(tokens_without_sw)
print(filtered_sentence)



filtered_sentence = (" ").join(tokens_without_sw)
print(filtered_sentence)

